
import Link from 'next/link';

export default function Footer() {
  return (
    <footer className="relative border-t border-border/60 bg-background">
<div className="mx-auto grid max-w-7xl gap-10 px-4 py-14 md:grid-cols-[1.5fr_1fr_1fr]"><div className="max-w-sm"><span className="inline-flex items-center gap-2"><span className="relative grid h-9 w-9 place-items-center rounded-xl [background-image:var(--gradient-primary)] shadow-glow"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="lucide lucide-shield-plus h-5 w-5 text-primary-foreground" aria-hidden="true"><path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z"></path><path d="M9 12h6"></path><path d="M12 9v6"></path></svg><span className="absolute inset-0 rounded-xl opacity-0 [background-image:var(--gradient-primary)] blur-md transition-opacity duration-500 group-hover:opacity-60"></span></span><span className="font-display text-lg font-extrabold tracking-tight">Medi<span className="text-gradient">Vault</span></span></span><p className="mt-4 text-sm leading-relaxed text-muted-foreground">A complete, secure, and portable health history — from the moment of birth to the last consultation of life. Built for Nigerian hospitals, clinics and laboratories.</p></div><div><h4 className="text-sm font-semibold">Platform</h4><ul className="mt-4 space-y-2.5"><li><Link href="/platform" className="story-link text-sm text-muted-foreground transition-colors hover:text-foreground">Features</Link></li><li><Link href="/how-it-works" className="story-link text-sm text-muted-foreground transition-colors hover:text-foreground">How it works</Link></li><li><Link href="/security" className="story-link text-sm text-muted-foreground transition-colors hover:text-foreground">Security &amp; compliance</Link></li></ul></div><div><h4 className="text-sm font-semibold">Company</h4><ul className="mt-4 space-y-2.5"><li><Link href="/contact" className="story-link text-sm text-muted-foreground transition-colors hover:text-foreground">Contact</Link></li><li><Link href="/auth" className="story-link text-sm text-muted-foreground transition-colors hover:text-foreground">Sign in</Link></li></ul></div></div><div className="border-t border-border/60"><div className="mx-auto flex max-w-7xl flex-col gap-2 px-4 py-6 text-xs text-muted-foreground sm:flex-row sm:items-center sm:justify-between"><p>© 2026 MediVault Inc. All rights reserved.</p><p>NDPA 2023 · HL7 FHIR · ISO 27001 aligned</p></div></div>
</footer>
  );
}
